<?php

namespace DoctrineProxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Persoon extends \Persoon implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNaam()
    {
        $this->__load();
        return parent::getNaam();
    }

    public function setNaam($Naam)
    {
        $this->__load();
        return parent::setNaam($Naam);
    }

    public function getAchternaam()
    {
        $this->__load();
        return parent::getAchternaam();
    }

    public function setAchternaam($Achternaam)
    {
        $this->__load();
        return parent::setAchternaam($Achternaam);
    }

    public function getGeboortedatum()
    {
        $this->__load();
        return parent::getGeboortedatum();
    }

    public function setGeboortedatum($Geboortedatum)
    {
        $this->__load();
        return parent::setGeboortedatum($Geboortedatum);
    }

    public function getGeslacht()
    {
        $this->__load();
        return parent::getGeslacht();
    }

    public function setGeslacht($Geslacht)
    {
        $this->__load();
        return parent::setGeslacht($Geslacht);
    }

    public function getStudie()
    {
        $this->__load();
        return parent::getStudie();
    }

    public function setStudie($Studie)
    {
        $this->__load();
        return parent::setStudie($Studie);
    }

    public function getStudiejaar()
    {
        $this->__load();
        return parent::getStudiejaar();
    }

    public function setStudiejaar($Studiejaar)
    {
        $this->__load();
        return parent::setStudiejaar($Studiejaar);
    }

    public function getBijbaan()
    {
        $this->__load();
        return parent::getBijbaan();
    }

    public function setBijbaan($Bijbaan)
    {
        $this->__load();
        return parent::setBijbaan($Bijbaan);
    }

    public function getEetgewoonte()
    {
        $this->__load();
        return parent::getEetgewoonte();
    }

    public function setEetgewoonte($Eetgewoonte)
    {
        $this->__load();
        return parent::setEetgewoonte($Eetgewoonte);
    }

    public function getLoginnaam()
    {
        $this->__load();
        return parent::getLoginnaam();
    }

    public function setLoginnaam($Loginnaam)
    {
        $this->__load();
        return parent::setLoginnaam($Loginnaam);
    }

    public function getWachtwoord()
    {
        $this->__load();
        return parent::getWachtwoord();
    }

    public function setWachtwoord($Wachtwoord)
    {
        $this->__load();
        return parent::setWachtwoord($Wachtwoord);
    }

    public function wijzigGegevens()
    {
        $this->__load();
        return parent::wijzigGegevens();
    }

    public function verwijderAccount()
    {
        $this->__load();
        return parent::verwijderAccount();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'Loginnaam', 'Wachtwoord', 'Huurhoogte', 'Naam', 'Achternaam', 'Functierol', 'Geboortedatum', 'Geslacht', 'Studie', 'Studiejaar', 'Bijbaan', 'Eetgewoonte', 'Huis_Id', 'Transactie_Id', 'Taakpunt_id', 'Bericht_id', 'PersoonRoosterpunt_id', 'Kalenderpunt_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}